/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jon' at '3/15/15 10:18 AM' with Gradle 2.2.1
 *
 * @author jon, @date 3/15/15 10:18 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
